### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by DarthMotzkus** [L10N37/PS1-IGR-in-game-reset-PlayStation-Sony-psone#1]
Hi, i have some questions.
- Is this work with PSIO with the Short Reset?
- Should i buy an 3.3V/8mhz or 5V/16mhz ATMEGA328P Nano?
- Where exactly do i need to solder the wires on the arduino and in a pu-20 ps1 mb?

Thanks.

**Comment by L10N37** [comment]
The little LGT8F328P mini were all the same, pricing them differently as 3.3v/5v was a marketing trick. As for the larger boards usually just a regulator is added as the MCU pins are 5v tolerant. 3.3v will be your power source and should be fine.

Will work perfectly with PSIO.

Ground, 3.3v are easy, in fact all the connections are universal on every board if you use the rear of the controller ports for the serial / data points, to find the board connections you just buzz them across to the main board with a multimeter.

The easiest way is just use the points off other IGR installations which are documented already. The only difference is you are omitting a few connections not required on this IGR.

https://www.consolesunleashed.com/guides/sony-playstation-in-game-reset-install-guide/

**Comment by DarthMotzkus** [comment]
Great, thanks for the answers and explanations.
