### ISSUE TITLE
Question about flashing ATMega328P with the library mentioned

### ISSUE THREAD

**Issue by DarthMotzkus** [L10N37/PS1-IGR-in-game-reset-PlayStation-Sony-psone#2]
Hi. I have installed the library you mentioned, but which board should i select to work with the ATmega328P Nano?

![Screenshot 2024-09-04 212738](https://github.com/user-attachments/assets/0a2a4c03-904b-46c5-8e3d-dfcd1204629a)

I have read in someplace that to flash this board i should use another library (w/ Old Bootloader). Is your code work only with the library you mentioned?

I have this library from MCUDude which says it's compatible with my board, it could run your code?

![image](https://github.com/user-attachments/assets/dcf1b2f1-355a-4583-adbe-2d6e10aa04ba)

Or the default AVR Nano Boards library...

![image](https://github.com/user-attachments/assets/3886cb70-ab58-412e-866c-62687556db80)

Thanks!

**Comment by L10N37** [comment]
I switched to LGT8F328P for most projects as they were considerably cheaper, initially I ditched them until I discovered the issues were with timing (and my projects all being heavily timing based) .

I found library that for most projects resolved any issues encountered so when I mention using a specific library it only applies to the LGT8F328P boards.

For the regular atmega (or clone atmega) MCU you can just stick to default libraries generally packaged and updated automatically with the Arduino IDE installation

**Comment by L10N37** [comment]
Also to nir

**Comment by L10N37** [comment]
also for this project you can flash normally with bootloader over USB or bootloader-less with my ubernee guide (covering LGT8F328L) 

the delay caused by the bootloader doesn't affect the serial capture, its self correcting and always starts at the first byte

**Comment by DarthMotzkus** [comment]
Thanks man, much appreciate.
