### ISSUE TITLE
Can't install library

### ISSUE THREAD

**Issue by Pabletex91** [L10N37/PS1-IGR-in-game-reset-PlayStation-Sony-psone#3]
Hi! I'm trying to do this mod, but i can't install the "lgt8f-1.0.7-alpha.1" library, it shows this message 
![image](https://github.com/user-attachments/assets/e4d4a137-a8ab-49ba-8e68-eed6c1091dcf)
I'm using the purple board with usb controller. 

INB4: first time using the IDE hahaha.

**Comment by L10N37** [comment]
Maybe you haven't unzipped the archive?

**Comment by Pabletex91** [comment]
> Maybe you haven't unzipped the archive?

I tried both, zip and unzipped, also i read that the ide version 2.x.x doesn't support .zip libraries anymore (?)  and that if it is not valid, it is because it is not an arduino library.

As I said before, this is my first time using the IDE, so I don't know what i'm doing wrong.

**Comment by L10N37** [comment]
There are more thorough instructions somewhere in a text file on the ubernee repo

**Comment by Pabletex91** [comment]
I already uploaded the code, but i'm not sure if this is the correct way: I installed a hardware package for the board that the seller provided me, and i included manually the "lgt328p" folder from the zip in documents/arduino/libraries folder because no one .zip let me install as library. 

![image](https://github.com/user-attachments/assets/1746c3df-7ea8-4c81-9e61-e8e9cbda7047)
![image](https://github.com/user-attachments/assets/8d867d04-b69a-48c6-8f2d-697f31d26b8a)
![image](https://github.com/user-attachments/assets/8b41c902-c1e9-42d9-b25d-70af6e32ca75)

**Comment by Pabletex91** [comment]
I'm not sure if this is the correct way: I installed the latest board manager from the same author of that .zip (the IDE simply not let me install any library), and now recognizes the board, then uploaded the code. 

![image](https://github.com/user-attachments/assets/82b0242a-2a5a-4327-a7f7-c7d27c8e28c0)
![image](https://github.com/user-attachments/assets/d8d17376-4094-44d8-8dd1-06a70557292a)

I will solder now and try it.

**Comment by L10N37** [comment]
It might work on this off memory but the delay for a long reset would have to modified, maybe to 2200 to 2500. To use the suggested library you have to manually install it by removing the old library and putting the files from the zip archive in its place. You can't install the sugested library through the IDE.

**Comment by Pabletex91** [comment]
> It might work on this off memory but the delay for a long reset would have to modified, maybe to 2200 to 2500. To use the suggested library you have to manually install it by removing the old library and putting the files from the zip archive in its place. You can't install the sugested library through the IDE.

I manually replaced the library with the 1.0.7 and works perfectly (sorry again for being so noob with Arduino). Also changed the delay to 2200 to make sure it works and voilá. 

Thank you for your time and obviously for your work! 

![IMG-20240920-WA0025](https://github.com/user-attachments/assets/b0651b52-ab9a-4827-bbcc-5a783f721e2f)
![IMG-20240921-WA0003](https://github.com/user-attachments/assets/2f4b6a5e-2ca9-422c-9330-25f75b0e43ed)

**Comment by L10N37** [comment]
No worries! the library you installed manually has really good timing and 2000 is 2 seconds as it's accurate and good for a long reset. 2200 won't hurt won't though. It's just the other libraries that aren't accurate enough and 2000 works out to under a 2 second reset so both combos would just reset the to game played and not return to menu. For code with heavuer reliance on timing the other libraries don't cut it. 

Glad it's sorted, enjoy !
